<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Kino DB application')->setSeparator(' - ')->setAutoEscape(false)?>

        <?=$this->headMeta()->
        appendName('viewport', 'width=device-width, initial-scale=1.0')->
        appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?= $this->headLink()->
        appendStylesheet($this->basePath('/lib/bootstrap/css/bootstrap.min.css'))->
        appendStylesheet($this->basePath('/style/style.css'))?>

        <!-- Scripts -->
        <?=$this->headScript()->
        appendFile($this->basePath('lib/moment.min.js'))->
        appendFile($this->basePath('lib/prefixfree.min.js'))->
        appendFile($this->basePath('lib/jquery-3.2.1.min.js'))->
        appendFile($this->basePath('lib/underscore-min.js'))->
        appendFile($this->basePath('lib/backbone-min.js'))->
        appendFile($this->basePath('lib/raty-2.5.2/lib/jquery.raty.js'))->
        appendFile($this->basePath('lib/bootstrap/js/bootstrap.min.js'))->
        appendFile($this->basePath('src/master.js'))?>
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>
