<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Kino DB application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()->
        appendName('viewport', 'width=device-width, initial-scale=1.0')->
        appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- Le styles -->
        <?= $this->headLink()->
        appendStylesheet($this->basePath('/lib/bootstrap/css/bootstrap.min.css'))->
        appendStylesheet($this->basePath('/css/style.css')) ?>

        <!-- Scripts -->
        <?= $this->headScript()->setAllowArbitraryAttributes(true)->
        appendFile('/lib/require.js', $type = 'text/javascript', $attrs = array("data-main" => "/js/main.js")) ?>
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>
